version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- ps: >-
    cd src

    .\build.ps1 -target AppVeyor
test: off
artifacts:
- path: src\*.nupkg
  name: nupkg
- path: '**\TestResult.xml'
  name: test results

cache:
- src\packages -> src\**\packages.config
- src\tools -> build.cake
